//! Parallel/serial gate calibration for the neural-network kernels
//!
//! Every `*_MIN_FLOPS` / `*_MIN_OPS` / `*_PARALLEL_THRESHOLD` constant in the crate decides when
//! a pass is worth spreading across rayon. This bench times the **forced-serial** and
//! **forced-parallel** implementations of each kernel class across a size ladder, prints the
//! tables, and rewrites `benches/RESULTS.md` with the measurements and the observed crossovers,
//! so the constants can be set from data instead of estimates.
//!
//! Run with:
//!
//! ```text
//! cargo bench --bench parallel_gates
//! ```
//!
//! Calibration is machine-specific; the generated report records the CPU and thread count.
//!
//! The calibrations are grouped by kernel family:
//!
//! - [`harness`]: the timing loop, the `Row`/`Section` table model, and the random-data generators
//! - [`matmul`]: GEMM/GEMV FLOP and block gates plus the GEMM-strategy shootouts
//! - [`nn_kernels`]: conv/pooling engines and the f32 elementwise classes
//! - [`ml_kernels`]: f64 elementwise classes and the deterministic blocked reductions
//! - [`trees`]: tree traversal/sort-scan/build and the kd-tree dimension crossover
//! - [`normalization`]: BatchNorm and LayerNorm statistics folds

mod harness;
mod matmul;
mod ml_kernels;
mod nn_kernels;
mod normalization;
mod trees;

use std::fmt::Write as _;

fn cpu_model() -> String {
    std::fs::read_to_string("/proc/cpuinfo")
        .ok()
        .and_then(|s| {
            s.lines()
                .find(|l| l.starts_with("model name"))
                .and_then(|l| l.split(':').nth(1))
                .map(|m| m.trim().to_string())
        })
        .unwrap_or_else(|| "unknown".to_string())
}

fn today() -> String {
    std::process::Command::new("date")
        .arg("+%Y-%m-%d")
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|| "unknown".to_string())
}

fn main() {
    // `cargo bench -- <filter>` passes harness args; this custom harness ignores them
    let threads = rayon::current_num_threads();
    println!("calibrating parallel gates (rayon threads: {threads}) ...");

    let mut sections = vec![
        matmul::calibrate_par_matmul_flops(),
        matmul::calibrate_par_matmul_min_block(),
        nn_kernels::calibrate_conv_forward(),
        nn_kernels::calibrate_pooling(),
    ];
    sections.extend(nn_kernels::calibrate_elementwise());
    sections.push(matmul::calibrate_par_matmul_flops_f64());
    sections.push(matmul::calibrate_par_matmul_min_block_f64());
    sections.push(matmul::calibrate_par_matvec_flops_f32());
    sections.push(matmul::calibrate_par_matvec_flops_f64());
    sections.extend(matmul::calibrate_par_matvec_min_block());
    sections.extend(ml_kernels::calibrate_elementwise_f64());
    sections.extend(matmul::calibrate_gemm_chunk_budget());
    sections.push(matmul::calibrate_pairwise_strategy());
    sections.push(trees::calibrate_tree_traversal());
    sections.push(trees::calibrate_sort_scan());
    sections.push(trees::calibrate_tree_build());
    sections.push(ml_kernels::calibrate_det_reduce_block());
    sections.push(ml_kernels::calibrate_exp_reduction());
    sections.push(ml_kernels::calibrate_kmeans_accumulate());
    sections.push(ml_kernels::calibrate_f32_sq_sum());
    sections.push(ml_kernels::calibrate_det_reduce_block_f32());
    sections.push(normalization::calibrate_bn_col_stats());
    sections.push(normalization::calibrate_bn_col_stats_rowblock());
    sections.push(normalization::calibrate_bn_plane_stats());
    sections.push(normalization::calibrate_ln_row_pass());
    sections.push(nn_kernels::calibrate_spatial_dropout_scale());
    sections.push(trees::calibrate_kd_tree_dims());

    for s in &sections {
        s.print();
    }

    // Rewrite the report
    let mut md = String::new();
    let _ = writeln!(md, "# Parallel-gate calibration results\n");
    let _ = writeln!(
        md,
        "Generated by `cargo bench --bench parallel_gates`. Do not edit by hand - rerun instead.\n"
    );
    let _ = writeln!(md, "- CPU: {}", cpu_model());
    let _ = writeln!(md, "- rayon threads: {threads}");
    let _ = writeln!(md, "- date: {}\n", today());
    let _ = writeln!(
        md,
        "Each table forces the **serial** and **parallel** implementation of one kernel class on \
         either side of its gate and reports the speedup per ladder rung; the gate constant \
         should sit at the crossover (with a small safety margin toward serial).\n"
    );
    for s in &sections {
        s.to_markdown(&mut md);
    }
    let _ = writeln!(
        md,
        "## End-to-end benchmarks\n\nThe end-to-end numbers are tracked separately by criterion: \
         `cargo bench --bench nn_end_to_end` (neural-network layer forwards, a training epoch) and \
         `cargo bench --bench ml_end_to_end --features full` (classical-ML/utils fits, predicts, \
         and transforms); detailed reports and saved baselines live under `target/criterion/` \
         (use `-- --save-baseline <name>` / `-- --baseline <name>` to compare across changes)."
    );

    let path = std::path::Path::new("benches/RESULTS.md");
    std::fs::write(path, md).expect("write benches/RESULTS.md");
    println!("\nwrote {}", path.display());
}
