//! Matrix products for ndarray operands, backed by the [`gemmkit`](https://docs.rs/gemmkit)
//! engine (through its zero-copy [`gemmkit-ndarray`](https://docs.rs/gemmkit-ndarray) adapter)
//!
//! Every product runs on gemmkit's kernels - runtime-dispatched to the widest available SIMD
//! (AVX-512F / FMA / NEON / wasm simd128 over a scalar floor), with operand packing, and
//! automatic reroutes for the bandwidth-bound shapes (matvec `n == 1`, small-`m,n`, small-`k`).
//! Scheduling is gemmkit's own:
//!
//! - **Auto parallelism** (`Parallelism::Rayon(0)`, the `gemm_par_auto` / `gemv_par_auto`
//!   default): a work gate (`m*n*k` below `GEMMKIT_PARALLEL_THRESHOLD` runs serial, so the tiny
//!   products in tight loops - RNN/LSTM timesteps - skip the dispatch cost entirely), then a
//!   work-based worker ramp snapped to persistent exact-fit thread-pool tiers. A matvec instead
//!   gates on bytes touched against an LLC-derived floor and jumps to a memory-bandwidth cap -
//!   the backend parallelizes GEMV itself, so this crate no longer row-splits by hand
//! - **Forced serial** (`gemm_par_switch` / `gemv_par_switch` with `parallel == false`,
//!   `Parallelism::Serial`): still gemmkit's SIMD kernel, on the calling thread only. Callers
//!   inside an already-parallel rayon region use this so the product does not fork again
//!
//! Calls made from inside a rayon worker run on the caller's pool (gemmkit detects nesting), so
//! these wrappers also compose safely inside a rayon region
//!
//! ## Tuning
//!
//! The scheduling knobs live in gemmkit, not this crate: every threshold is a `GEMMKIT_*`
//! environment variable (read once per process), programmatically settable via
//! [`crate::tuning::matmul::backend`], and a whole-machine profile can be generated by the
//! [`gemmkit-tune`](https://docs.rs/gemmkit-tune) autotuner and `source`d before launch
//!
//! ## Reproducibility
//!
//! gemmkit's blocking and job order are independent of the worker count, so for a fixed machine
//! and configuration the same product reproduces the same result bit-for-bit, no matter how many
//! threads ran it (and re-running is deterministic). Fused epilogues (bias / activation / map)
//! are bitwise-identical to the plain product followed by the same scalar map
//!
//! `gemm_chunk_rows` and `cache_resident` remain as tiling-strategy helpers for callers that
//! materialize a product in row-chunks (KNN, t-SNE, MeanShift)

#[cfg(feature = "machine_learning")]
use ndarray::{Array1, Ix1};
#[cfg(any(
    feature = "machine_learning",
    feature = "neural_network",
    feature = "utils"
))]
use ndarray::{Array2, ArrayBase, Data, Ix2};

/// `C = A @ B` with explicit parallelism control, both arms on gemmkit's kernels
///
/// `A` is `(m, k)`, `B` is `(k, n)`; the result is a freshly allocated, standard-layout `(m, n)`
/// array. Any storage works (owned, view, transpose, slice; strides pass through zero-copy)
///
/// - `parallel == false`: one serial gemmkit call (`Parallelism::Serial`) - still the SIMD
///   kernel, just on one thread. Use this to force a product serial from inside an
///   already-parallel region, so it does not fork rayon again (nested parallelism /
///   oversubscription)
/// - `parallel == true`: gemmkit auto parallelism (`Parallelism::Rayon(0)`) - the backend gates
///   serial-vs-parallel on the work size and picks the worker count and split itself
///
/// Callers with no opinion on parallelism should use [`gemm_par_auto`] instead
///
/// # Panics
///
/// - If `A`'s column count differs from `B`'s row count
#[cfg(any(
    feature = "machine_learning",
    feature = "neural_network",
    feature = "utils"
))]
pub(crate) fn gemm_par_switch<T, S1, S2>(
    a: &ArrayBase<S1, Ix2>,
    b: &ArrayBase<S2, Ix2>,
    parallel: bool,
) -> Array2<T>
where
    T: gemmkit::GemmScalar,
    S1: Data<Elem = T>,
    S2: Data<Elem = T>,
{
    let (m, k) = a.dim();
    let (kb, n) = b.dim();
    assert_eq!(
        k, kb,
        "gemm_par_switch: inner dimensions disagree (a is {m}x{k}, b is {kb}x{n})",
    );
    let par = if parallel {
        gemmkit::Parallelism::Rayon(0)
    } else {
        gemmkit::Parallelism::Serial
    };
    // `beta == 0` means the fill value is never read; `from_elem` avoids a `Zero` bound
    let mut c = Array2::from_elem((m, n), T::ZERO);
    gemmkit_ndarray::gemm(T::ONE, a, b, T::ZERO, &mut c, par);
    c
}

/// `C = A @ B` on gemmkit's automatic scheduling
///
/// Serial below the backend's work gate (the per-call dispatch would dominate the tiny products
/// in tight loops, e.g. RNN/LSTM timesteps); above it the backend picks the worker count and the
/// split. This is the entry for callers that have no opinion on parallelism;
/// [`gemm_par_switch`] is the entry for callers that must control it explicitly
///
/// # Panics
///
/// - If `A`'s column count differs from `B`'s row count
#[cfg(any(
    feature = "machine_learning",
    feature = "neural_network",
    feature = "utils"
))]
pub(crate) fn gemm_par_auto<T, S1, S2>(a: &ArrayBase<S1, Ix2>, b: &ArrayBase<S2, Ix2>) -> Array2<T>
where
    T: gemmkit::GemmScalar,
    S1: Data<Elem = T>,
    S2: Data<Elem = T>,
{
    gemm_par_switch(a, b, true)
}

/// `y = A @ x` with explicit parallelism control (the GEMV analogue of [`gemm_par_switch`])
///
/// `A` is `(m, k)`, `x` has length `k`; the result has length `m`
/// - `parallel == false`: one serial gemmkit call. Use this to force a matvec serial from inside
///   an already-parallel region so it does not fork rayon again
/// - `parallel == true`: gemmkit auto parallelism - the backend detects the `n == 1` shape and
///   runs its bandwidth-bound GEMV path (serial below an LLC-derived byte floor, then split
///   across the memory-bandwidth worker cap)
///
/// Callers with no opinion on parallelism should use [`gemv_par_auto`] instead
///
/// # Panics
///
/// - If `A`'s column count differs from `x`'s length
#[cfg(feature = "machine_learning")]
pub(crate) fn gemv_par_switch<T, S1, S2>(
    a: &ArrayBase<S1, Ix2>,
    x: &ArrayBase<S2, Ix1>,
    parallel: bool,
) -> Array1<T>
where
    T: gemmkit::GemmScalar,
    S1: Data<Elem = T>,
    S2: Data<Elem = T>,
{
    use ndarray::Axis;

    let (m, k) = a.dim();
    assert_eq!(
        k,
        x.len(),
        "gemv_par_switch: inner dimensions disagree (a is {m}x{k}, x has length {})",
        x.len()
    );
    let par = if parallel {
        gemmkit::Parallelism::Rayon(0)
    } else {
        gemmkit::Parallelism::Serial
    };
    // Treat the vector as a single-column matrix; gemmkit reroutes `n == 1` to its GEMV path
    let x_col = x.view().insert_axis(Axis(1)); // [k, 1]
    let mut y = Array1::from_elem(m, T::ZERO);
    let mut y_col = y.view_mut().insert_axis(Axis(1)); // [m, 1]
    gemmkit_ndarray::gemm(T::ONE, a, &x_col, T::ZERO, &mut y_col, par);
    y
}

/// `y = A @ x` on gemmkit's automatic scheduling (the GEMV analogue of [`gemm_par_auto`])
///
/// `A` is `(m, k)`, `x` has length `k`; the result has length `m`. The backend gates the matvec
/// on bytes touched (a matvec is memory-bound: serial while the operands are cache-resident,
/// split across the bandwidth worker cap once they stream from DRAM)
///
/// # Panics
///
/// - If `A`'s column count differs from `x`'s length
#[cfg(feature = "machine_learning")]
pub(crate) fn gemv_par_auto<T, S1, S2>(a: &ArrayBase<S1, Ix2>, x: &ArrayBase<S2, Ix1>) -> Array1<T>
where
    T: gemmkit::GemmScalar,
    S1: Data<Elem = T>,
    S2: Data<Elem = T>,
{
    gemv_par_switch(a, x, true)
}

tunable_gate! {
    /// Element budget for one row-chunk of a tiled product whose full result would be too large
    /// to materialize at once (e.g. KNN's `[n_query, n_train]` projections or t-SNE's pairwise
    /// blocks): `chunk_rows = gemm_chunk_elems() / row_len`, clamped to `[16, 4096]` rows
    ///
    /// Tiling only pays when the shared operand overflows the cache (see `cache_resident`); there
    /// bigger chunks are strictly better, so the budget caps the transient chunk buffer at 256 MB
    /// of `f64` rather than chasing the asymptote. Overridable via [`crate::tuning::matmul`]
    pub(crate) GEMM_CHUNK_ELEMS => gemm_chunk_elems / set_gemm_chunk_elems = 33_554_432
}

/// Rows per chunk when tiling a product with `row_len`-wide output rows under `gemm_chunk_elems`
///
/// Crate-internal tiling policy; not part of the public API and carries no stability guarantee
#[doc(hidden)]
pub fn gemm_chunk_rows(row_len: usize) -> usize {
    (gemm_chunk_elems() / row_len.max(1)).clamp(16, 4096)
}

tunable_gate! {
    /// Matrix size (bytes) below which repeated row-GEMV sweeps over a shared matrix stay
    /// cache-resident, making a per-row GEMV swarm faster than a tiled GEMM
    ///
    /// When many tasks each compute `X . v` against the same `X`, the whole of `X` is re-read per
    /// task - free while `X` fits in the shared L3, but a DRAM re-stream once it overflows, where a
    /// tiled GEMM (which streams `X` once per chunk) wins instead. The default sits at a typical
    /// L3 size; the band around it is uncalibrated. Overridable via [`crate::tuning::matmul`] - the
    /// natural knob to match a machine's actual L3
    pub(crate) CACHE_RESIDENT_MAX_BYTES
        => cache_resident_max_bytes / set_cache_resident_max_bytes = 64 * 1024 * 1024
}

/// Whether an `[rows, cols]` matrix of `T` is small enough to treat as cache-resident for
/// repeated row-GEMV sweeps (see `cache_resident_max_bytes`)
///
/// Crate-internal strategy policy; not part of the public API and carries no stability
/// guarantee
#[doc(hidden)]
pub fn cache_resident<T>(rows: usize, cols: usize) -> bool {
    rows.saturating_mul(cols)
        .saturating_mul(std::mem::size_of::<T>())
        < cache_resident_max_bytes()
}

#[cfg(all(
    test,
    any(
        feature = "machine_learning",
        feature = "neural_network",
        feature = "utils"
    )
))]
mod tests {
    use super::*;
    #[cfg(feature = "machine_learning")]
    use ndarray::Array1;
    use ndarray::{Array2, LinalgScalar, s};

    /// Deterministic pseudo-random matrices (hash-based, no rng dependency)
    fn rand_f32(r: usize, c: usize, seed: u64) -> Array2<f32> {
        Array2::from_shape_fn((r, c), |(i, j)| {
            let t = (seed as f64) * 0.731 + (i * c + j) as f64 * 0.618_033_988_7;
            ((t.sin() * 43758.5453).fract() - 0.5) as f32
        })
    }
    fn rand_f64(r: usize, c: usize, seed: u64) -> Array2<f64> {
        Array2::from_shape_fn((r, c), |(i, j)| {
            let t = (seed as f64) * 0.731 + (i * c + j) as f64 * 0.618_033_988_7;
            (t.sin() * 43758.5453).fract() - 0.5
        })
    }

    /// Independent triple-loop reference product (same element type, fixed k-order)
    fn naive<T: LinalgScalar>(a: &Array2<T>, b: &Array2<T>) -> Array2<T> {
        let (m, k) = a.dim();
        let n = b.ncols();
        let mut c = Array2::<T>::zeros((m, n));
        for i in 0..m {
            for j in 0..n {
                let mut acc = T::zero();
                for p in 0..k {
                    acc = acc + a[[i, p]] * b[[p, j]];
                }
                c[[i, j]] = acc;
            }
        }
        c
    }

    fn assert_close_f32(got: &Array2<f32>, want: &Array2<f32>, eps: f32) {
        assert_eq!(got.shape(), want.shape());
        for (g, w) in got.iter().zip(want.iter()) {
            assert!((g - w).abs() <= eps, "f32 mismatch: {g} vs {w}");
        }
    }
    fn assert_close_f64(got: &Array2<f64>, want: &Array2<f64>, eps: f64) {
        assert_eq!(got.shape(), want.shape());
        for (g, w) in got.iter().zip(want.iter()) {
            assert!((g - w).abs() <= eps, "f64 mismatch: {g} vs {w}");
        }
    }

    // correctness vs an independent reference

    /// gemm_par_auto matches the naive product for f32 on both sides of the backend's work gate
    /// (`m*n*k` 589,824 by default)
    #[test]
    fn gemm_par_auto_matches_reference_f32() {
        for &(m, k, n) in &[
            (17usize, 23usize, 19usize), /* tiny, serial */
            (64, 48, 64),                /* below the gate */
        ] {
            let a = rand_f32(m, k, 1);
            let b = rand_f32(k, n, 2);
            assert_close_f32(&gemm_par_auto(&a, &b), &naive(&a, &b), 1e-2);
        }
        // Above the gate (256*300*256 ~ 19.7M): cross-check against ndarray's own dot
        let a = rand_f32(256, 300, 3);
        let b = rand_f32(300, 256, 4);
        assert_close_f32(&gemm_par_auto(&a, &b), &a.dot(&b), 1e-2);
    }

    /// gemm_par_auto matches the reference for f64 on both sides of the work gate
    #[test]
    fn gemm_par_auto_matches_reference_f64() {
        for &(m, k, n) in &[
            (17usize, 23usize, 19usize),
            (64, 64, 64), /* below the gate */
        ] {
            let a = rand_f64(m, k, 1);
            let b = rand_f64(k, n, 2);
            assert_close_f64(&gemm_par_auto(&a, &b), &naive(&a, &b), 1e-9);
        }
        // Above the gate (128^3 ~ 2.1M)
        let a = rand_f64(128, 128, 3);
        let b = rand_f64(128, 128, 4);
        assert_close_f64(&gemm_par_auto(&a, &b), &a.dot(&b), 1e-9);
    }

    /// Transposed and non-contiguous (sliced) operands feed the right strides to the kernel
    #[test]
    fn gemm_par_auto_strided_operands() {
        // A^T . B (the weight-gradient pattern): a is [k, m], a.t() is [m, k]
        let a = rand_f64(40, 24, 5);
        let b = rand_f64(40, 18, 6);
        let got = gemm_par_auto(&a.t(), &b);
        let want = naive(&a.t().to_owned(), &b);
        assert_close_f64(&got, &want, 1e-9);

        // Row-strided slice of A times a column-strided slice of B
        let a = rand_f64(40, 30, 7);
        let b = rand_f64(30, 40, 8);
        let a_sl = a.slice(s![..;2, ..]); // [20, 30], row stride 60
        let b_sl = b.slice(s![.., ..;2]); // [30, 20], col stride 2
        let got = gemm_par_auto(&a_sl, &b_sl);
        let want = naive(&a_sl.to_owned(), &b_sl.to_owned());
        assert_close_f64(&got, &want, 1e-9);
    }

    /// Thin-output GEMM (`n` a handful, above the work gate) - the shape the old hand-rolled
    /// row split existed for - is correct on the backend's own scheduling
    #[test]
    fn gemm_par_auto_thin_output() {
        // f64: 4096*64*4 = 1.05M above the gate, n = 4
        let a = rand_f64(4096, 64, 61);
        let b = rand_f64(64, 4, 62);
        assert_close_f64(&gemm_par_auto(&a, &b), &a.dot(&b), 1e-9);
        // f32: 16384*64*4 = 4.2M above the gate
        let a = rand_f32(16384, 64, 63);
        let b = rand_f32(64, 4, 64);
        assert_close_f32(&gemm_par_auto(&a, &b), &a.dot(&b), 1e-2);
    }

    // the reproducibility guard

    /// The backend's contract: for a fixed config the result is identical no matter how many
    /// workers ran it. Serial and forced-parallel also agree bitwise on the current kernels
    /// (both run the same kernel with thread-count-independent blocking)
    #[test]
    fn gemm_thread_count_independent_f64() {
        // square, dense, and a thin-k shape (the one most likely to trigger a split-k reduction)
        for &(m, k, n) in &[(96usize, 96usize, 96usize), (256, 64, 64), (64, 8192, 64)] {
            let a = rand_f64(m, k, 11);
            let b = rand_f64(k, n, 12);
            let serial = gemm_par_switch(&a, &b, false);
            for threads in [2usize, 4, 8, 16, 32] {
                let mut par = Array2::from_elem((m, n), 0.0f64);
                gemmkit_ndarray::gemm(
                    1.0,
                    &a,
                    &b,
                    0.0,
                    &mut par,
                    gemmkit::Parallelism::Rayon(threads),
                );
                assert!(
                    serial
                        .iter()
                        .zip(par.iter())
                        .all(|(s, p)| s.to_bits() == p.to_bits()),
                    "gemm f64 {m}x{k}x{n} differs between serial and Rayon({threads})"
                );
            }
        }
    }

    /// Same worker-count-independence check for f32
    #[test]
    fn gemm_thread_count_independent_f32() {
        for &(m, k, n) in &[(96usize, 96usize, 96usize), (64, 8192, 64)] {
            let a = rand_f32(m, k, 13);
            let b = rand_f32(k, n, 14);
            let serial = gemm_par_switch(&a, &b, false);
            for threads in [2usize, 4, 32] {
                let mut par = Array2::from_elem((m, n), 0.0f32);
                gemmkit_ndarray::gemm(
                    1.0,
                    &a,
                    &b,
                    0.0,
                    &mut par,
                    gemmkit::Parallelism::Rayon(threads),
                );
                assert!(
                    serial
                        .iter()
                        .zip(par.iter())
                        .all(|(s, p)| s.to_bits() == p.to_bits()),
                    "gemm f32 {m}x{k}x{n} differs between serial and Rayon({threads})"
                );
            }
        }
    }

    /// Running the same product twice on the same machine gives the same result (this test asserts
    /// bit-level equality)
    #[test]
    fn gemm_par_auto_run_to_run_deterministic() {
        let a = rand_f64(200, 200, 21);
        let b = rand_f64(200, 200, 22);
        let c1 = gemm_par_auto(&a, &b);
        let c2 = gemm_par_auto(&a, &b);
        assert!(
            c1.iter()
                .zip(c2.iter())
                .all(|(x, y)| x.to_bits() == y.to_bits())
        );
    }

    // the epilogue guard: fused bias+activation is bitwise-identical to the unfused pipeline

    /// gemmkit's fused epilogue contract for f32/f64: `gemm_fused` equals plain `gemm` followed
    /// by the same scalar bias-add and activation, bit for bit. The NN layers rely on this to
    /// fuse bias + ReLU without changing numerics
    #[test]
    fn gemm_fused_bias_relu_bitwise_matches_unfused() {
        let a = rand_f32(64, 48, 31);
        let b = rand_f32(48, 40, 32);
        let bias: Vec<f32> = (0..40).map(|j| (j as f32) * 0.05 - 1.0).collect();

        let mut fused = Array2::from_elem((64, 40), 0.0f32);
        gemmkit_ndarray::gemm_fused(
            1.0,
            &a,
            &b,
            0.0,
            &mut fused,
            Some(gemmkit_ndarray::Bias::PerCol(&bias)),
            Some(gemmkit_ndarray::Activation::Relu),
            gemmkit::Parallelism::Rayon(0),
        );

        let mut want = gemm_par_auto(&a, &b);
        for mut row in want.rows_mut() {
            for (v, bj) in row.iter_mut().zip(bias.iter()) {
                *v = (*v + bj).max(0.0);
            }
        }
        assert!(
            fused
                .iter()
                .zip(want.iter())
                .all(|(f, w)| f.to_bits() == w.to_bits()),
            "fused bias+ReLU differs from the unfused pipeline"
        );
    }

    // gemv

    /// gemv_par_auto matches the reference on both cache-resident and larger shapes
    #[cfg(feature = "machine_learning")]
    #[test]
    fn gemv_par_auto_matches_reference() {
        for &(m, k) in &[(40usize, 24usize), (8192, 64)] {
            let a = rand_f64(m, k, 31);
            let x = Array1::from_shape_fn(k, |i| ((i as f64) * 0.37).sin());
            let got = gemv_par_auto(&a, &x);
            let want = a.dot(&x);
            assert_eq!(got.len(), want.len());
            for (g, w) in got.iter().zip(want.iter()) {
                assert!((g - w).abs() <= 1e-9, "gemv mismatch: {g} vs {w}");
            }
        }
    }

    /// Forced-serial and auto GEMV agree bitwise (the backend reduces each output element over
    /// the full `k` on one worker, so the matvec is bit-identical at any worker count)
    #[cfg(feature = "machine_learning")]
    #[test]
    fn gemv_serial_and_auto_agree_bitwise() {
        let a = rand_f64(8192, 64, 41);
        let x = Array1::from_shape_fn(64, |i| ((i as f64) * 0.59).sin());
        let serial = gemv_par_switch(&a, &x, false);
        let auto = gemv_par_auto(&a, &x);
        assert_eq!(serial.len(), auto.len());
        assert!(
            serial
                .iter()
                .zip(auto.iter())
                .all(|(s, p)| s.to_bits() == p.to_bits()),
            "gemv serial vs auto differ"
        );
    }

    /// GEMV is run-to-run deterministic on the same machine
    #[cfg(feature = "machine_learning")]
    #[test]
    fn gemv_par_auto_run_to_run_deterministic() {
        let a = rand_f64(8192, 64, 51);
        let x = Array1::from_shape_fn(64, |i| ((i as f64) * 0.23).sin());
        let y1 = gemv_par_auto(&a, &x);
        let y2 = gemv_par_auto(&a, &x);
        assert!(
            y1.iter()
                .zip(y2.iter())
                .all(|(a, b)| a.to_bits() == b.to_bits())
        );
    }

    // degenerate shapes

    #[test]
    fn gemm_par_auto_edge_cases() {
        // zero-sized axes (handled inside gemmkit: `m == 0`/`n == 0` write nothing, `k == 0`
        // leaves `beta * C`, which is all zeros here)
        let a = Array2::<f64>::zeros((0, 4));
        let b = Array2::<f64>::zeros((4, 3));
        assert_eq!(gemm_par_auto(&a, &b).shape(), &[0, 3]);
        let a = Array2::<f64>::zeros((3, 0));
        let b = Array2::<f64>::zeros((0, 4));
        let c = gemm_par_auto(&a, &b);
        assert_eq!(c.shape(), &[3, 4]);
        assert!(c.iter().all(|&x| x == 0.0));
        // 1x1
        let a = Array2::<f64>::from_elem((1, 1), 3.0);
        let b = Array2::<f64>::from_elem((1, 1), 4.0);
        assert_eq!(gemm_par_auto(&a, &b)[[0, 0]], 12.0);
    }

    #[test]
    #[should_panic]
    fn gemm_par_auto_dimension_mismatch_panics() {
        let a = Array2::<f64>::zeros((2, 3));
        let b = Array2::<f64>::zeros((4, 2));
        let _ = gemm_par_auto(&a, &b);
    }
}
