//! Parallel/serial gate calibration for the crate's kernels
//!
//! Every `*_MIN_FLOPS` / `*_MIN_OPS` / `*_PARALLEL_THRESHOLD` constant in the crate decides when
//! a pass is worth spreading across rayon. This bench times the forced-serial and
//! forced-parallel implementations of each kernel class across a size ladder. It prints the
//! tables and rewrites `benches/calibrations/RESULTS.md` with the measurements, so the
//! constants can be set from data instead of estimates.
//!
//! Run with:
//!
//! ```text
//! cargo bench --bench parallel_gates
//! ```
//!
//! Calibration is machine-specific. The generated report records the CPU and the thread count.
//!
//! The calibrations are grouped by kernel family. See the doc comment above each `mod`
//! declaration below for what it covers.

/// The timing loop, the `Row`/`Section` table model, and the random-data generators.
mod harness;
/// f64 elementwise classes and the deterministic blocked reductions.
mod ml_kernels;
/// Conv and pooling engines plus the f32 elementwise classes.
mod nn_kernels;
/// BatchNorm and LayerNorm statistics folds.
mod normalization;
/// Tree traversal, sort-scan, tree build, and the kd-tree dimension crossover.
mod trees;

use std::fmt::Write as _;

fn cpu_model() -> String {
    std::fs::read_to_string("/proc/cpuinfo")
        .ok()
        .and_then(|s| {
            s.lines()
                .find(|l| l.starts_with("model name"))
                .and_then(|l| l.split(':').nth(1))
                .map(|m| m.trim().to_string())
        })
        .unwrap_or_else(|| "unknown".to_string())
}

fn today() -> String {
    std::process::Command::new("date")
        .arg("+%Y-%m-%d")
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|| "unknown".to_string())
}

fn main() {
    // `cargo bench -- <filter>` passes harness args. This custom harness ignores them.
    let threads = rayon::current_num_threads();
    println!("calibrating parallel gates (rayon threads: {threads}) ...");

    // The matmul backend (`gemmkit`) decides serial-vs-parallel by problem size on its own, so
    // this harness has no GEMM or GEMV gate to calibrate.
    let mut sections = vec![
        nn_kernels::calibrate_conv_forward(),
        nn_kernels::calibrate_pooling(),
    ];
    sections.extend(nn_kernels::calibrate_elementwise());
    sections.extend(ml_kernels::calibrate_elementwise_f64());
    sections.push(trees::calibrate_tree_traversal());
    sections.push(trees::calibrate_sort_scan());
    sections.push(trees::calibrate_tree_build());
    sections.push(ml_kernels::calibrate_det_reduce_block());
    sections.push(ml_kernels::calibrate_exp_reduction());
    sections.push(ml_kernels::calibrate_kmeans_accumulate());
    sections.push(ml_kernels::calibrate_f32_sq_sum());
    sections.push(ml_kernels::calibrate_det_reduce_block_f32());
    sections.push(normalization::calibrate_bn_col_stats());
    sections.push(normalization::calibrate_bn_col_stats_rowblock());
    sections.push(normalization::calibrate_bn_plane_stats());
    sections.push(normalization::calibrate_ln_row_pass());
    sections.push(nn_kernels::calibrate_spatial_dropout_scale());
    sections.push(trees::calibrate_kd_tree_dims());

    for s in &sections {
        s.print();
    }

    let mut md = String::new();
    let _ = writeln!(md, "# Parallel-gate calibration results\n");
    let _ = writeln!(
        md,
        "Generated by `cargo bench --bench parallel_gates`. Do not edit by hand - rerun instead.\n"
    );
    let _ = writeln!(md, "- CPU: {}", cpu_model());
    let _ = writeln!(md, "- rayon threads: {threads}");
    let _ = writeln!(md, "- date: {}\n", today());
    let _ = writeln!(
        md,
        "Each table forces the **serial** and **parallel** implementation of one kernel class on \
         either side of its gate and reports the speedup per ladder rung; the gate constant \
         should sit at the crossover (with a small safety margin toward serial).\n"
    );
    for s in &sections {
        s.to_markdown(&mut md);
    }
    let _ = writeln!(
        md,
        "## End-to-end benchmarks\n\nThe end-to-end numbers are tracked separately by criterion: \
         `cargo bench --bench nn_end_to_end` (neural-network layer forwards, a training epoch) and \
         `cargo bench --bench ml_end_to_end --features full` (classical-ML/utils fits, predicts, \
         and transforms); detailed reports and saved baselines live under `target/criterion/` \
         (use `-- --save-baseline <name>` / `-- --baseline <name>` to compare across changes)."
    );

    let path = std::path::Path::new("benches/calibrations/RESULTS.md");
    std::fs::write(path, md).expect("write benches/calibrations/RESULTS.md");
    println!("\nwrote {}", path.display());
}
